#pragma config(Motor,  port2,           Lmotor,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           Rmotor,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Sensor, dgtl1,  leftEncoder,     sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void moveFor(int time)
{
	 clearTimer(T1);

	 while(time1[T1]<time){
	 motor[Rmotor] = 127;
   motor[Rmotor] = 127;

   motor[Lmotor] = 127;
   motor[Lmotor] = 127;}

}
void drivR(int time){
	while(time1[T1]<time){
	 motor[Rmotor] = -20;
   motor[Rmotor] = -20;

   motor[Lmotor] = 127;
   motor[Lmotor] = 127;}
}

void autR()
{
	  moveFor(1000);

	  drivR(2000);
	  moveFor(2000);



}

task main()
{


while(true) {

   // right side = Channel 2 joystick value
   motor[Rmotor] = vexRT[Ch2];
   motor[Rmotor] = vexRT[Ch2];

   // left side = Channel 3 joystick value
   motor[Lmotor] = vexRT[Ch3];
   motor[Lmotor] = vexRT[Ch3];

   if(vexRT(Btn7D) == 1){
     autR();

     }


}



}
