#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           Pulley,        tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           Lmotor,        tmotorVex269_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Pincer,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           Rmotor,        tmotorVex269_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void pullUp(){
 motor[Pulley] = 127;
}

void letDown(){
motor[Pulley] = -127;	
}

void close() {
motor[Pincer] = -127;	
}


void open() {
motor[Pincer] = 127;	
}


void moveFor(int time)
{
	 clearTimer(T1);

	 while(time1[T1]<time){
	 motor[Rmotor] = 127;
   motor[Rmotor] = 127;

   motor[Lmotor] = 127;
   motor[Lmotor] = 127;}

}
void drivR(int time){
	while(time1[T1]<time){
	 motor[Rmotor] = -20;
   motor[Rmotor] = -20;

   motor[Lmotor] = 127;
   motor[Lmotor] = 127;}
}

void autR()
{
	  moveFor(1000);

	  drivR(2000);
	  moveFor(2000);



}

task main()
{


while(true) {

   // right side = Channel 2 joystick value
   motor[Rmotor] = vexRT[Ch2];
   motor[Rmotor] = vexRT[Ch2];

   // left side = Channel 3 joystick value
   motor[Lmotor] = vexRT[Ch3];
   motor[Lmotor] = vexRT[Ch3];

   if(vexRT(Btn7D) == 1){
     autR();

     }
    if(vexRT(Btn6U) == 1){
     	pullUp();
    }
    if(vexRT(Btn6D) == 1){
     	letDown();
    }


}



}
