#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port3,           Pulley,        tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           Lmotor,        tmotorVex269_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           Pincer,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           Rmotor,        tmotorVex269_MC29, openLoop, reversed, driveRight)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void moveFor(int time)
{
	 clearTimer(T1);

	 while(time1[T1]<time){
	 motor[Rmotor] = 127;
   motor[Rmotor] = 127;

   motor[Lmotor] = 127;
   motor[Lmotor] = 127;}

}
void drivR(int time){
	clearTimer(T1);
	while(time1[T1]<time){
	 motor[Rmotor] = -20;
   motor[Rmotor] = -20;

   motor[Lmotor] = 127;
   motor[Lmotor] = 127;}
}

void autR()
{
	  moveFor(1500);

	  drivR(1000);
	  moveFor(1501);



}

task main()
{

short armMode = -1;
short slowMode = -1;
short holdMode = -1;

while(true) {

  if(armMode == -1){

   if(slowMode == -1){
   // right side = Channel 2 joystick value
   motor[Rmotor] = vexRT[Ch2];
   motor[Rmotor] = vexRT[Ch2];

   // left side = Channel 3 joystick value
   motor[Lmotor] = vexRT[Ch3];
   motor[Lmotor] = vexRT[Ch3];}

   if(slowMode == 1){
        // right side = Channel 2 joystick value
   motor[Rmotor] = vexRT[Ch2]*.3;
   motor[Rmotor] = vexRT[Ch2]*.3;

   // left side = Channel 3 joystick value
   motor[Lmotor] = vexRT[Ch3]*.3;
   motor[Lmotor] = vexRT[Ch3]*.3;}
 }


if(armMode == 1){
	if (slowMode == -1){
   motor[Pincer] = 	vexRT[Ch4];
   motor[Pulley] = vexRT[Ch2];
}
 if(slowMode == 1){
    motor[Pincer] = 	vexRT[Ch4]*.3;
   motor[Pulley] = vexRT[Ch2]*.3;
 }
}
if(holdMode == 1){
   motor[Pincer] = 127;
}



   if(vexRT(Btn7D) == 1){
     autR();

     }

//to change to modes
if(vexRT(Btn8U) == 1){
  armMode *= -1;
  wait1Msec(250);
}

 if(vexRT(Btn8D) == 1){
  slowMode *= -1;
  wait1Msec(250);

}
if(vexRT(Btn7U) == 1){
  holdMode *=-1;
  wait1Msec(250);

}
//code ends here

}
}
